//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNotifier.View.NotifyServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotifyServiceWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonitorNotifications", ReplyAction="http://tempuri.org/IService1/MonitorNotificationsResponse")]
        void MonitorNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MonitorNotifications", ReplyAction="http://tempuri.org/IService1/MonitorNotificationsResponse")]
        System.Threading.Tasks.Task MonitorNotificationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastRestartTime", ReplyAction="http://tempuri.org/IService1/GetLastRestartTimeResponse")]
        System.Nullable<System.DateTime> GetLastRestartTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastRestartTime", ReplyAction="http://tempuri.org/IService1/GetLastRestartTimeResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.DateTime>> GetLastRestartTimeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SmartNotifier.View.NotifyServiceWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SmartNotifier.View.NotifyServiceWCF.IService1>, SmartNotifier.View.NotifyServiceWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void MonitorNotifications() {
            base.Channel.MonitorNotifications();
        }
        
        public System.Threading.Tasks.Task MonitorNotificationsAsync() {
            return base.Channel.MonitorNotificationsAsync();
        }
        
        public System.Nullable<System.DateTime> GetLastRestartTime() {
            return base.Channel.GetLastRestartTime();
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.DateTime>> GetLastRestartTimeAsync() {
            return base.Channel.GetLastRestartTimeAsync();
        }
    }
}
