//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNotifier.View.NotifyServiceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotifyServiceWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastRestartTime", ReplyAction="http://tempuri.org/IService1/GetLastRestartTimeResponse")]
        System.Nullable<System.DateTime> GetLastRestartTime();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLastRestartTime", ReplyAction="http://tempuri.org/IService1/GetLastRestartTimeResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.DateTime>> GetLastRestartTimeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSystemInforamtion", ReplyAction="http://tempuri.org/IService1/GetSystemInforamtionResponse")]
        SmartNotifier.Common.SystemInforamtion GetSystemInforamtion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSystemInforamtion", ReplyAction="http://tempuri.org/IService1/GetSystemInforamtionResponse")]
        System.Threading.Tasks.Task<SmartNotifier.Common.SystemInforamtion> GetSystemInforamtionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDriveInforamtion", ReplyAction="http://tempuri.org/IService1/GetDriveInforamtionResponse")]
        SmartNotifier.Common.DriveInformation GetDriveInforamtion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDriveInforamtion", ReplyAction="http://tempuri.org/IService1/GetDriveInforamtionResponse")]
        System.Threading.Tasks.Task<SmartNotifier.Common.DriveInformation> GetDriveInforamtionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetConsoleProcesses", ReplyAction="http://tempuri.org/IService1/GetConsoleProcessesResponse")]
        SmartNotifier.Common.ConsoleProcesses[] GetConsoleProcesses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetConsoleProcesses", ReplyAction="http://tempuri.org/IService1/GetConsoleProcessesResponse")]
        System.Threading.Tasks.Task<SmartNotifier.Common.ConsoleProcesses[]> GetConsoleProcessesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetConsoleInformation", ReplyAction="http://tempuri.org/IService1/GetConsoleInformationResponse")]
        SmartNotifier.Common.ConsoleInformation GetConsoleInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetConsoleInformation", ReplyAction="http://tempuri.org/IService1/GetConsoleInformationResponse")]
        System.Threading.Tasks.Task<SmartNotifier.Common.ConsoleInformation> GetConsoleInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetConsoleEventLogInformation", ReplyAction="http://tempuri.org/IService1/GetConsoleEventLogInformationResponse")]
        SmartNotifier.Common.ConsoleEventLogs[] GetConsoleEventLogInformation(int loginterval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetConsoleEventLogInformation", ReplyAction="http://tempuri.org/IService1/GetConsoleEventLogInformationResponse")]
        System.Threading.Tasks.Task<SmartNotifier.Common.ConsoleEventLogs[]> GetConsoleEventLogInformationAsync(int loginterval);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SmartNotifier.View.NotifyServiceWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SmartNotifier.View.NotifyServiceWCF.IService1>, SmartNotifier.View.NotifyServiceWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<System.DateTime> GetLastRestartTime() {
            return base.Channel.GetLastRestartTime();
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.DateTime>> GetLastRestartTimeAsync() {
            return base.Channel.GetLastRestartTimeAsync();
        }
        
        public SmartNotifier.Common.SystemInforamtion GetSystemInforamtion() {
            return base.Channel.GetSystemInforamtion();
        }
        
        public System.Threading.Tasks.Task<SmartNotifier.Common.SystemInforamtion> GetSystemInforamtionAsync() {
            return base.Channel.GetSystemInforamtionAsync();
        }
        
        public SmartNotifier.Common.DriveInformation GetDriveInforamtion() {
            return base.Channel.GetDriveInforamtion();
        }
        
        public System.Threading.Tasks.Task<SmartNotifier.Common.DriveInformation> GetDriveInforamtionAsync() {
            return base.Channel.GetDriveInforamtionAsync();
        }
        
        public SmartNotifier.Common.ConsoleProcesses[] GetConsoleProcesses() {
            return base.Channel.GetConsoleProcesses();
        }
        
        public System.Threading.Tasks.Task<SmartNotifier.Common.ConsoleProcesses[]> GetConsoleProcessesAsync() {
            return base.Channel.GetConsoleProcessesAsync();
        }
        
        public SmartNotifier.Common.ConsoleInformation GetConsoleInformation() {
            return base.Channel.GetConsoleInformation();
        }
        
        public System.Threading.Tasks.Task<SmartNotifier.Common.ConsoleInformation> GetConsoleInformationAsync() {
            return base.Channel.GetConsoleInformationAsync();
        }
        
        public SmartNotifier.Common.ConsoleEventLogs[] GetConsoleEventLogInformation(int loginterval) {
            return base.Channel.GetConsoleEventLogInformation(loginterval);
        }
        
        public System.Threading.Tasks.Task<SmartNotifier.Common.ConsoleEventLogs[]> GetConsoleEventLogInformationAsync(int loginterval) {
            return base.Channel.GetConsoleEventLogInformationAsync(loginterval);
        }
    }
}
